#!/bin/bash
# Project guardrail: blocks Edit/Write on generated, vendored, or confirm-first files.
# Exit 0 = allow, Exit 2 = block (reason via stderr)
#
# The global hook (~/.claude/hooks/protect-files.sh) already covers .env*,
# .claude/settings*.json and node_modules/. Do not re-implement those here.

INPUT=$(cat)
FILE_PATH=$(echo "$INPUT" | jq -r '.tool_input.file_path // empty')

if [ -z "$FILE_PATH" ]; then
  exit 0
fi

REL_PATH="${FILE_PATH#"$CLAUDE_PROJECT_DIR"/}"

# --- Block: lockfile ---
if [[ "$REL_PATH" == "package-lock.json" ]]; then
  echo "Protected: package-lock.json is managed by npm. Run 'npm install <pkg>' instead." >&2
  exit 2
fi

# --- Block: build and report output ---
case "$REL_PATH" in
  .next/* | out/* | dist/* | coverage/* | reports/* | .vercel/*)
    echo "Protected: '$REL_PATH' is build output. Change the source, then rebuild." >&2
    exit 2
    ;;
  cypress/videos/* | cypress/screenshots/*)
    echo "Protected: Cypress artifacts are generated by test runs." >&2
    exit 2
    ;;
esac

# --- Block: generated CSS bundle ---
if [[ "$REL_PATH" == "src/styles/output.css" ]]; then
  echo "Protected: src/styles/output.css is generated. Edit src/styles/** and run 'npm run build:css'." >&2
  exit 2
fi

# --- Block: synced OpenAPI snapshot ---
if [[ "$REL_PATH" == "docs/reference/api/lakira-backend-openapi.json" ]]; then
  echo "Protected: the OpenAPI snapshot is synced from lakira-backend, never hand-edited. Run 'npm run api:spec:sync'." >&2
  exit 2
fi

# --- Block: generated API types ---
if [[ "$REL_PATH" == src/types/api/generated/* ]]; then
  echo "Protected: '$REL_PATH' is generated from the OpenAPI snapshot. Run 'npm run api:types:generate'." >&2
  exit 2
fi

# --- Block: CI workflows (confirm with the user first) ---
case "$REL_PATH" in
  .github/workflows/*.yml | .github/workflows/*.yaml)
    echo "Protected: CI workflows change what runs on every push. Confirm with the user before editing '$REL_PATH'." >&2
    exit 2
    ;;
esac

exit 0
